# This file is part of the Home Assistant role.
#
# Copyright (c) 2023 Rafael Milani Barbosa <rafaelmilanib@gmail.com>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- include: preparation.yml
- include: motd.yml
  when: motd_modification | default(false)
- include: installation.yml
- include: systemd.yml
- include: firewall.yml
  when: ansible_distribution == "Debian"
