# This file is part of the Home Assistant role.
#
# Copyright (c) 2023 Rafael Milani Barbosa <rafaelmilanib@gmail.com>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- name: install commonly-named packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - python3
  - python3-pip
  - gcc

- name: install fedora-specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-firewall
    - python3-devel
    - redhat-rpm-config
    - python2
    - python2-dnf
    - libselinux-python
    - firewalld
    - which
  when: ansible_distribution == "Fedora"

- name: install debian-specific packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-dev
  when: ansible_distribution == "Debian"

- name: install debian-required pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - appdirs
    - packaging
  when: ansible_distribution == "Debian"

- name: create user
  user:
    name: "{{ ha_user }}"
    comment: "Home Assistant"
    system: yes
    shell: "/sbin/nologin"

- name: create directory
  file:
    path: "{{ ha_conf_dir }}"
    state: directory
    mode: 02775
    owner: "{{ ha_user }}"
    group: "{{ ha_user }}"
