# This file is part of the Home Assistant role.
#
# Copyright (c) 2023 Rafael Milani Barbosa <rafaelmilanib@gmail.com>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- name: restart home-assistant
  service:
    name: home-assistant
    state: restarted
